name = "KeldyshContraction"
uuid = "da6be1f2-7f61-475e-9253-2fea1ca4beca"
authors = ["Orjan Ameye <orjan.ameye@hotmail.com>"]
version = "0.1.0-DEV"

[deps]
Combinatorics = "861a8166-3701-5b0c-9a16-15d98fcdc6aa"
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
LaTeXStrings = "b964fa9f-0449-5b57-a5c2-d3ea65f4040f"
Latexify = "23fbe1c1-3f47-55db-b15f-69d7ec21a316"
MacroTools = "1914dd2f-81c6-5fcd-8719-6d5c9610ff09"
OrderedCollections = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"
SmallCollections = "2b935e18-93d6-40ac-ae34-fe54c09f00e1"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
SymbolicUtils = "d1185830-fcd6-423d-90d6-eec64667417b"
TermInterface = "8ea1fca8-c5ef-4a55-8b96-4e9afe9c9a3c"

[compat]
Aqua = "0.8.11"
CheckConcreteStructs = "0.1"
Combinatorics = "1"
DocStringExtensions = "0.9.4"
ExplicitImports = "1.11"
JET = "0.9.18, 0.10"
LaTeXStrings = "1.4"
Latexify = "0.16"
MacroTools = "0.5.15"
OrderedCollections = "1.8.0"
SmallCollections = "0.4.0"
SymbolicUtils = "3.26"
StaticArrays = "1.9.13"
TermInterface = "2"
Test = "1.10"
julia = "1.10"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
CheckConcreteStructs = "73c92db5-9da6-4938-911a-6443a7e94a58"
ExplicitImports = "7d51a73a-1435-4ff3-83d9-f097790105c7"
JET = "c3a54625-cd67-489e-a8e7-0a5a0ff4e31b"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["JET", "CheckConcreteStructs", "ExplicitImports", "Test", "Aqua"]
